### PR TITLE
Add namespace

### PR DESCRIPTION
**Pull request by roanvanbao**

### CODE REVIEW

**Comment by peter279k** [comment]
Is anyone concern this PR?

**Comment by roanvanbao** [comment]
I don't know. I just created it for using in my library easier.

**Comment by peter279k** [comment]
@roanvanbao, it seems that this repo has not been alive for the long time...
I hope the owner can concern this and other issues :+1: .

**Comment by roanvanbao** [comment]
Yes, I think so too.

**Pull request closed without merging**
